on: push
name: Deploy website on push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
 
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
         server: node165-eu.n0c.com
         server-dir: /public_html/mesvoyages/
         username: quahamde
         password: ${{ secrets.ftp_password }}
